// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@twin.org/data-core";
import * as external0 from "@twin.org/data-json-ld";
const MESSAGES = ["must NOT have fewer than 3 items","must be equal to constant","must be array","must be string","must be boolean","must be object","must NOT have fewer than 1 items","must match a schema in anyOf"];
function createError(instancePath, schemaPath, keyword, params, message) {
return { instancePath, schemaPath, keyword, params, ["message"]: typeof message === "number" ? MESSAGES[message] : message };
}
function pushError(errors, error) {
if (errors === null) {
return [error];
}
errors.push(error);
return errors;
}
/**
 * Compiled validator for the AttestationInformation schema.
 */
export const CompiledAttestationInformation: ICompiledValidator = validate52;
const keyword0 = external0["CompiledJsonLdContextDefinitionElement"];
const keyword1 = external0["CompiledJsonLdNodeObject"];

function validate52(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/attestation/AttestationInformation" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate52.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.id === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "id"},"must have required property '"+"id"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data.dateCreated === undefined){
const err3 = createError(instancePath,"#/required","required",{missingProperty: "dateCreated"},"must have required property '"+"dateCreated"+"'");
vErrors = pushError(vErrors, err3);
errors++;
}
if(data.ownerIdentity === undefined){
const err4 = createError(instancePath,"#/required","required",{missingProperty: "ownerIdentity"},"must have required property '"+"ownerIdentity"+"'");
vErrors = pushError(vErrors, err4);
errors++;
}
if(data.attestationObject === undefined){
const err5 = createError(instancePath,"#/required","required",{missingProperty: "attestationObject"},"must have required property '"+"attestationObject"+"'");
vErrors = pushError(vErrors, err5);
errors++;
}
if(data["@context"] !== undefined){
let data0 = data["@context"];
if(Array.isArray(data0)){
if(data0.length < 3){
const err6 = createError(instancePath+"/@context","#/properties/%40context/minItems","minItems",{limit: 3},0);
vErrors = pushError(vErrors, err6);
errors++;
}
const len0 = data0.length;
if(len0 > 0){
if("https://schema.org" !== data0[0]){
const err7 = createError(instancePath+"/@context/0","#/properties/%40context/prefixItems/0/const","const",{allowedValue: "https://schema.org"},1);
vErrors = pushError(vErrors, err7);
errors++;
}
}
if(len0 > 1){
if("https://schema.twindev.org/attestation/" !== data0[1]){
const err8 = createError(instancePath+"/@context/1","#/properties/%40context/prefixItems/1/const","const",{allowedValue: "https://schema.twindev.org/attestation/"},1);
vErrors = pushError(vErrors, err8);
errors++;
}
}
if(len0 > 2){
if("https://schema.twindev.org/common/" !== data0[2]){
const err9 = createError(instancePath+"/@context/2","#/properties/%40context/prefixItems/2/const","const",{allowedValue: "https://schema.twindev.org/common/"},1);
vErrors = pushError(vErrors, err9);
errors++;
}
}
const len1 = data0.length;
var valid2 = len1 <= 3;
if(!valid2){
for(let i0=3; i0<len1; i0++){
const _errs6 = errors;
if(!(keyword0(data0[i0], {instancePath:instancePath+"/@context/" + i0,parentData:data0,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
errors = vErrors.length;
}
var valid2 = _errs6 === errors;
}
}
}
else {
const err10 = createError(instancePath+"/@context","#/properties/%40context/type","type",{type: "array"},2);
vErrors = pushError(vErrors, err10);
errors++;
}
}
if(data.type !== undefined){
if("Information" !== data.type){
const err11 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "Information"},1);
vErrors = pushError(vErrors, err11);
errors++;
}
}
if(data.id !== undefined){
if(typeof data.id !== "string"){
const err12 = createError(instancePath+"/id","#/properties/id/type","type",{type: "string"},3);
vErrors = pushError(vErrors, err12);
errors++;
}
}
if(data.dateCreated !== undefined){
if(typeof data.dateCreated !== "string"){
const err13 = createError(instancePath+"/dateCreated","#/properties/dateCreated/type","type",{type: "string"},3);
vErrors = pushError(vErrors, err13);
errors++;
}
}
if(data.dateTransferred !== undefined){
if(typeof data.dateTransferred !== "string"){
const err14 = createError(instancePath+"/dateTransferred","#/properties/dateTransferred/type","type",{type: "string"},3);
vErrors = pushError(vErrors, err14);
errors++;
}
}
if(data.ownerIdentity !== undefined){
if(typeof data.ownerIdentity !== "string"){
const err15 = createError(instancePath+"/ownerIdentity","#/properties/ownerIdentity/type","type",{type: "string"},3);
vErrors = pushError(vErrors, err15);
errors++;
}
}
if(data.attestationObject !== undefined){
if(!(keyword1(data.attestationObject, {instancePath:instancePath+"/attestationObject",parentData:data,parentDataProperty:"attestationObject",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
if(data.proof !== undefined){
if(!(keyword1(data.proof, {instancePath:instancePath+"/proof",parentData:data,parentDataProperty:"proof",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
if(data.verified !== undefined){
if(typeof data.verified !== "boolean"){
const err16 = createError(instancePath+"/verified","#/properties/verified/type","type",{type: "boolean"},4);
vErrors = pushError(vErrors, err16);
errors++;
}
}
if(data.verificationFailure !== undefined){
if(typeof data.verificationFailure !== "string"){
const err17 = createError(instancePath+"/verificationFailure","#/properties/verificationFailure/type","type",{type: "string"},3);
vErrors = pushError(vErrors, err17);
errors++;
}
}
}
else {
const err18 = createError(instancePath,"#/type","type",{type: "object"},5);
vErrors = pushError(vErrors, err18);
errors++;
}
validate52.errors = vErrors;
return errors === 0;
}
validate52.evaluated = {"props":{"@context":true,"type":true,"id":true,"dateCreated":true,"dateTransferred":true,"ownerIdentity":true,"attestationObject":true,"proof":true,"verified":true,"verificationFailure":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the AttestationJwtProof schema.
 */
export const CompiledAttestationJwtProof: ICompiledValidator = validate53;

function validate53(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/attestation/AttestationJwtProof" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate53.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.value === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "value"},"must have required property '"+"value"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data["@context"] !== undefined){
let data0 = data["@context"];
const _errs2 = errors;
let valid1 = false;
const _errs3 = errors;
if("https://schema.twindev.org/attestation/" !== data0){
const err3 = createError(instancePath+"/@context","#/properties/%40context/anyOf/0/const","const",{allowedValue: "https://schema.twindev.org/attestation/"},1);
vErrors = pushError(vErrors, err3);
errors++;
}
var _valid0 = _errs3 === errors;
valid1 = valid1 || _valid0;
const _errs4 = errors;
if(Array.isArray(data0)){
if(data0.length < 1){
const err4 = createError(instancePath+"/@context","#/properties/%40context/anyOf/1/minItems","minItems",{limit: 1},6);
vErrors = pushError(vErrors, err4);
errors++;
}
const len0 = data0.length;
if(len0 > 0){
if("https://schema.twindev.org/attestation/" !== data0[0]){
const err5 = createError(instancePath+"/@context/0","#/properties/%40context/anyOf/1/prefixItems/0/const","const",{allowedValue: "https://schema.twindev.org/attestation/"},1);
vErrors = pushError(vErrors, err5);
errors++;
}
}
const len1 = data0.length;
var valid3 = len1 <= 1;
if(!valid3){
for(let i0=1; i0<len1; i0++){
const _errs7 = errors;
if(!(keyword0(data0[i0], {instancePath:instancePath+"/@context/" + i0,parentData:data0,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
errors = vErrors.length;
}
var valid3 = _errs7 === errors;
}
}
}
else {
const err6 = createError(instancePath+"/@context","#/properties/%40context/anyOf/1/type","type",{type: "array"},2);
vErrors = pushError(vErrors, err6);
errors++;
}
var _valid0 = _errs4 === errors;
valid1 = valid1 || _valid0;
if(!valid1){
const err7 = createError(instancePath+"/@context","#/properties/%40context/anyOf","anyOf",{},7);
vErrors = pushError(vErrors, err7);
errors++;
}
else {
errors = _errs2;
if(vErrors !== null){
if(_errs2){
vErrors.length = _errs2;
}
else {
vErrors = null;
}
}
}
}
if(data.type !== undefined){
if("JwtProof" !== data.type){
const err8 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "JwtProof"},1);
vErrors = pushError(vErrors, err8);
errors++;
}
}
if(data.value !== undefined){
if(typeof data.value !== "string"){
const err9 = createError(instancePath+"/value","#/properties/value/type","type",{type: "string"},3);
vErrors = pushError(vErrors, err9);
errors++;
}
}
}
else {
const err10 = createError(instancePath,"#/type","type",{type: "object"},5);
vErrors = pushError(vErrors, err10);
errors++;
}
validate53.errors = vErrors;
return errors === 0;
}
validate53.evaluated = {"props":{"@context":true,"type":true,"value":true},"dynamicProps":false,"dynamicItems":false};

